<#
    .SYNOPSIS
    Install N-ABle probe (Windows)

    .DESCRIPTION
    Install N-ABle probe (Windows)

    .PARAMETER AGENTACTIVATIONKEY
    The key generated by SolarWinds N-central that is required in order to install generic system agent software.

    .PARAMETER SERVERPROTOCOL
    Identifies the protocol that the probe will use to communicate with the central server as one of HTTP or HTTPS.

    .PARAMETER SERVERADDRESS
    The IP address or FQDN of the central server.

    .PARAMETER SERVERPORT
    The numeric port number that the probe will use to communicate with the central server. For example, 80 for HTTP or 443 for HTTPS.

    .PARAMETER PROBETYPE
    Identifies the type of probe to be installed as one of:

    - Local_Windows
    - Network_Windows (For this probe type, include the AGENTDOMAIN, AGENTUSERNAME, and AGENTPASSWORD parameters.)
    - Workgroup_Windows (For this probe type, include only the AGENTUSERNAME and AGENTPASSWORD parameters.)

    .PARAMETER AGENTDOMAIN	
    The domain of the user account that will access the probe. This parameter is only used for Windows probes and not for Windows agents.

    .PARAMETER AGENTUSERNAME	
    The user name of the user account that will access the probe.This parameter is only used for Windows probes and not for Windows agents.

    .PARAMETER AGENTPASSWORD	
    The password of the user account that will access the probe. This parameter is only used for Windows probes and not for Windows agents.

    .EXAMPLE
    PS> Install-NAbleWindowsProbe "02ac69e6-af38-32db-e923-7b64ebcc8d4e" "156"

    .NOTES
    Author: Jerome Couette (jerome.couette@cpu.ca)
    Version: 1.0.0
    Date: 2021-03-09
#>
function Install-NAbleWindowsProbe {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,Position=0)]
        [string]$AGENTACTIVATIONKEY,
        [Parameter(Mandatory=$false,Position=1)]
        [string]$SERVERPROTOCOL = "HTTPS",
        [Parameter(Mandatory=$false,Position=2)]
        [string]$SERVERADDRESS = "ncod440.n-able.com",
        [Parameter(Mandatory=$false,Position=3)]
        [string]$SERVERPORT = "443",
        [Parameter(Mandatory=$true,Position=4)]
        [string]$AGENTDOMAIN,
        [Parameter(Mandatory=$true,Position=5)]
        [string]$AGENTUSERNAME,
        [Parameter(Mandatory=$true,Position=6)]
        [string]$AGENTPASSWORD
    )
    Begin{
        $Global:ProbeInstallerURL = "http://chocolatey.cpu.qc.ca/endpoints/CPU/content/DEVOPS/NAble/WindowsProbeSetup.exe"
        $Global:ProbeInstallerPath = "$env:systemdrive\Temp\WindowsProbeSetup.exe"
        $Global:ProbeInstallerLog = "$env:systemdrive\Temp\probe_install.log"
    }
    Process{
        if (!(Test-Path "$env:systemdrive\Temp")) {mkdir "$env:systemdrive\Temp"}
        if (!(Test-Path "$env:systemdrive\Temp\WindowsAgentProbe.exe")) {
            Write-Host "Downloading probe installer..."
            Invoke-WebRequest -Uri $ProbeInstallerURL -Headers @{"AUTHORIZATION"="Basic " + [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("DefaultFeedUser:RC8QCsIKUe"))} -OutFile "$ProbeInstallerPath"
        }else {
            Write-Host "Agent installer file is already downloaded!"
        }
        if (Test-Path $ProbeInstallerPath) {
            Write-Host "Installing N-Able probe.."
            &$ProbeInstallerPath /s /v" /qn AGENTACTIVATIONKEY=$AGENTACTIVATIONKEY PROBETYPE=Network_Windows AGENTDOMAIN=$AGENTDOMAIN AGENTUSERNAME=$AGENTUSERNAME AGENTPASSWORD=$AGENTPASSWORD SERVERADDRESS=$SERVERADDRESS SERVERPROTOCOL=$SERVERPROTOCOL SERVERPORT=$SERVERPORT /L*v $ProbeInstallerLog "
        }
    }
    End{

    }
}
if ($ServerProtocol -eq "HTTP" -and $ServerPort -eq "80") {
    Install-NAbleWindowsProbe -AGENTACTIVATIONKEY $ActivationKey -AGENTDOMAIN $Domain -AGENTUSERNAME $Username -AGENTPASSWORD $Password -SERVERPROTOCOL $Protocol -SERVERPORT $Port
}else {
    Install-NAbleWindowsProbe -AGENTACTIVATIONKEY $ActivationKey -AGENTDOMAIN $Domain -AGENTUSERNAME $Username -AGENTPASSWORD $Password -SERVERPROTOCOL $Protocol -SERVERPORT $Port
}
